<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder {
    public function run() {
        DB::table('users')->insert([
            'name' => 'Admin',
            'email' => 'admin@haventwined.com',
            'password' => bcrypt('password1234'),
            'email_verified_at' => now(),
            'remember_token' => Str::random(10),
        ]);
        $companyProfile = DB::table('company_profiles')->insertGetId([
            'name' => 'Haventwined',
            'description' => 'Haventwined adalah solusi inovatif untuk pengelolaan event, menghubungkan penyelenggara dengan tenant dan vendor terbaik di industri. Kami hadir untuk mengubah setiap momen spesial Anda menjadi kenangan yang tak terlupakan melalui perencanaan yang cermat, kreativitas tanpa batas, dan eksekusi yang profesional',
            'email' => 'support@haventwined.com',
            'whatsapp' => '082299449708',
            'banner' => json_encode(
                [
                    "https://res.cloudinary.com/dllhxulpv/image/upload/v1740306832/Screenshot_2025-02-23_170210_hjztzf.png",
                    "https://res.cloudinary.com/dllhxulpv/image/upload/v1740306832/Screenshot_2025-02-23_170158_bvxrjn.png",
                    "https://res.cloudinary.com/dllhxulpv/image/upload/v1740329253/haventwined/z9mu5t7fqeaauoahwtg6.png"
                ]
            ),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('events')->insert([
            [
                'name' => 'Chapel Night',
                'content' => 'Deskripsi event Chapel Night',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1100,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area food court City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Big Feastival',
                'content' => 'Deskripsi event The Big Feastival',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1000,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area utama City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FIP FEST 2021',
                'content' => 'Deskripsi event FIP FEST 2021',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1600,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Lantai 2 City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bazar Dialog',
                'content' => 'Deskripsi event Bazar Dialog',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1000,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area pameran City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chapel Night',
                'content' => 'Deskripsi event Chapel Night',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1000,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area food court City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Big Feastival',
                'content' => 'Deskripsi event The Big Feastival',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1400,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area utama City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FIP FEST 2021',
                'content' => 'Deskripsi event FIP FEST 2021',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1300,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Lantai 2 City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bazar Dialog',
                'content' => 'Deskripsi event Bazar Dialog',
                'category' => 'Festival, Fair, Bazaar',
                'theme' => 'Kuliner, Fashion, Kecantikan & Perawatan Diri',
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1000,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area pameran City Mall',
                'company_profile_id' => $companyProfile,
                'url' => '/images/event-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
